apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: vote
  labels:
    type: local
spec:
  storageClassName: db
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-voting-app/db"
