apiVersion: v1
kind: PersistentVolume
metadata:
  name: voting-app-pv
  namespace: vote
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-voting-app"
