apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: vote
  labels:
    type: local
spec:
  storageClassName: redis
  capacity:
    storage: 0.1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data-voting-app/redis"
